version: 2.1

jobs:
  build:
    working_directory: ~/reddit
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run:
          name: Build
          command: |
            python3 -m venv reddit-backend
            source reddit-backend/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Test
          command: |
            # Reactivate virtual environment
            source reddit-backend/bin/activate
            # Remove any coverage data from previous runs
            coverage erase
            # Set working directory for pytest
            export PYTHONPATH=$PWD
            # Compute coverage -- this generates raw file .coverage
            pytest --cov -v
            # Show coverage metrics on shell
            coverage report -m
            # Generate XML report
            coverage xml
            # Public report to codecov.io
            bash <(curl -s https://codecov.io/bash) -f tests/coverage/coverage.xml
