version: 2
docker:
  - image: circleci/python:3.9.1
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Python and Virtual Environment
          command: |
            python --version
            python -m venv reddit-backend
            source reddit-backend/bin/activate
            pip install --upgrade pip
            pip install --requirement requirements.txt
            export PYTHONPATH=$PWD
          name: Project Tests
          command: |
            pytest --cov
