version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Python and Virtual Environment
          command: |
            python --version
            python -m venv reddit-backend
            source reddit-backend/bin/activate
            pip install --upgrade pip
            pip install --requirement requirements.txt
            export PYTHONPATH=$PWD
            pytest --cov
