jobs:
  build:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run:
          name: Python and Virtual Environment
          command: |
            python --version
            python -m venv reddit-backend
            source reddit-backend/bin/activate
            pip install --upgrade pip
            export PYTHONPATH=$PWD
          name: Project
          command: |
            pip install --requirement requirements.txt
            pytest --cov
