version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - run:
          name: setup environment
          command: |
            export PYTHONPATH=$PWD
            python --version
            python -m venv reddit-backend
            source reddit-backend/bin/activate

      - run:
          name: setup project
          command: |
            pip install --upgrade pip
            echo $PYTHONPATH
            pip install --requirement requirements.txt

      - run:
          name: run tests and coverage
          command: |
            pytest --cov -v
            coverage report -m
            coverage xml
            bash <(curl -s https://codecov.io/bash) -f tests/coverage/coverage.xml
